version: '3.8'

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: preschool_management
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: database
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: preschool_management

volumes:
  db_data:
