version: '3.8'

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: preschool
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: database
      DATABASE_USER: user
      DATABASE_PASSWORD: userpassword
      DATABASE_NAME: preschool

volumes:
  db_data: